<?php

namespace App\Http\Controllers\v1\User;

use App\Helpers\ApiResponse;
use App\Http\Controllers\Controller;
use App\Http\Requests\User\TwoFactor\ConfirmAuthenticatorRequest;
use App\Http\Requests\User\TwoFactor\RenderQrCodeRequest;
use App\Http\Requests\User\TwoFactor\SwitchMethodRequest;
use App\Services\User\TwoFactorAuthService;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @group Users
 *
 * APIs for managing user accounts and security settings.
 *
 * @subgroup Two-Factor Authentication
 * @subgroupDescription Manage authenticator app two-factor authentication for the authenticated user.
 */
class TwoFactorAuthController extends Controller
{
    public function __construct(
        private readonly TwoFactorAuthService $twoFactorAuthService
    ) {}

    /**
     * Render Authenticator QR Code
     *
     * Render the QR code SVG for authenticator app setup.
     *
     * @authenticated
     */
    public function renderAuthenticatorQrCode(RenderQrCodeRequest $request): Response
    {
        $svg = $this->twoFactorAuthService->renderAuthenticatorQrCode(
            user: $request->user(),
            secret: $request->validated('secret')
        );

        return response($svg, 200, [
            'Content-Type' => 'image/svg+xml',
            'Cache-Control' => 'no-store, no-cache, must-revalidate, max-age=0',
        ]);
    }

    /**
     * Generate Authenticator Setup
     *
     * Generate the authenticator app setup details for the authenticated user.
     * This returns a secret, otpauth URL, and QR code that can be scanned
     * using apps like Google Authenticator, Authy, or Microsoft Authenticator.
     *
     * @authenticated
     */
    public function setupAuthenticator(Request $request)
    {
        $data = $this->twoFactorAuthService->setupAuthenticator(
            $request->user()
        );

        return ApiResponse::success(
            'Authenticator setup generated successfully',
            $data
        );
    }

    /**
     * Confirm Authenticator Setup
     *
     * Confirm authenticator app enrollment by submitting a valid
     * 6-digit code generated by the authenticator app.
     *
     * Once confirmed, two-factor authentication will be enabled
     * and recovery codes will be generated.
     *
     * @authenticated
     */
    public function confirmAuthenticator(ConfirmAuthenticatorRequest $request)
    {
        $data = $this->twoFactorAuthService->confirmAuthenticator(
            user: $request->user(),
            secret: $request->validated('secret'),
            code: $request->validated('code')
        );

        return ApiResponse::success(
            'Authenticator 2FA enabled successfully',
            $data
        );
    }

    /**
     * Enable Two-Factor Authentication
     *
     * Turn two-factor authentication on for the authenticated user, using
     * whichever medium is currently selected (email by default, or a
     * previously configured authenticator app).
     *
     * @authenticated
     */
    public function enable(Request $request)
    {
        $this->twoFactorAuthService->enable(
            $request->user()
        );

        return ApiResponse::success(
            'Two-factor authentication enabled successfully'
        );
    }

    /**
     * Disable Two-Factor Authentication
     *
     * Turn two-factor authentication off for the authenticated user. The
     * active medium and any authenticator app configuration are kept, so
     * re-enabling later doesn't require setting anything up again.
     *
     * @authenticated
     */
    public function disable(Request $request)
    {
        $this->twoFactorAuthService->disable(
            $request->user()
        );

        return ApiResponse::success(
            'Two-factor authentication disabled successfully'
        );
    }

    /**
     * Switch Two-Factor Method
     *
     * Switch which medium two-factor authentication uses, independently of
     * whether it's currently on or off. Switching to the authenticator app
     * requires one to already be set up.
     *
     * @authenticated
     */
    public function switchMethod(SwitchMethodRequest $request)
    {
        $this->twoFactorAuthService->switchMethod(
            user: $request->user(),
            method: $request->validated('method')
        );

        return ApiResponse::success(
            'Two-factor method updated successfully'
        );
    }

    /**
     * Regenerate Recovery Codes
     *
     * Generate a new set of recovery codes for authenticator-based
     * two-factor authentication.
     *
     * Recovery codes can be used to access the account if the
     * authenticator device is unavailable.
     *
     * @authenticated
     */
    public function regenerateRecoveryCodes(Request $request)
    {
        $data = $this->twoFactorAuthService->regenerateRecoveryCodes(
            $request->user()
        );

        return ApiResponse::success(
            'Recovery codes regenerated successfully',
            $data
        );
    }
}