<?php

namespace App\Http\Controllers\v1\User;

use App\Helpers\ApiResponse;
use App\Http\Controllers\Controller;
use App\Http\Requests\User\TwoFactor\ConfirmAuthenticatorRequest;
use App\Http\Requests\User\TwoFactor\RenderQrCodeRequest;
use App\Services\User\TwoFactorAuthService;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @group Users
 *
 * APIs for managing user accounts and security settings.
 *
 * @subgroup Two-Factor Authentication
 * @subgroupDescription Manage authenticator app two-factor authentication for the authenticated user.
 */
class TwoFactorAuthController extends Controller
{
    public function __construct(
        private readonly TwoFactorAuthService $twoFactorAuthService
    ) {}

    /**
     * Render Authenticator QR Code
     *
     * Render the QR code SVG for authenticator app setup.
     *
     * @authenticated
     */
    public function renderAuthenticatorQrCode(RenderQrCodeRequest $request): Response
    {
        $svg = $this->twoFactorAuthService->renderAuthenticatorQrCode(
            user: $request->user(),
            secret: $request->validated('secret')
        );

        return response($svg, 200, [
            'Content-Type' => 'image/svg+xml',
            'Cache-Control' => 'no-store, no-cache, must-revalidate, max-age=0',
        ]);
    }

    /**
     * Generate Authenticator Setup
     *
     * Generate the authenticator app setup details for the authenticated user.
     * This returns a secret, otpauth URL, and QR code that can be scanned
     * using apps like Google Authenticator, Authy, or Microsoft Authenticator.
     *
     * @authenticated
     */
    public function setupAuthenticator(Request $request)
    {
        $data = $this->twoFactorAuthService->setupAuthenticator(
            $request->user()
        );

        return ApiResponse::success(
            'Authenticator setup generated successfully',
            $data
        );
    }

    /**
     * Confirm Authenticator Setup
     *
     * Confirm authenticator app enrollment by submitting a valid
     * 6-digit code generated by the authenticator app.
     *
     * Once confirmed, two-factor authentication will be enabled
     * and recovery codes will be generated.
     *
     * @authenticated
     */
    public function confirmAuthenticator(ConfirmAuthenticatorRequest $request)
    {
        $data = $this->twoFactorAuthService->confirmAuthenticator(
            user: $request->user(),
            secret: $request->validated('secret'),
            code: $request->validated('code')
        );

        return ApiResponse::success(
            'Authenticator 2FA enabled successfully',
            $data
        );
    }

    /**
     * Disable Authenticator 2FA
     *
     * Disable authenticator-based two-factor authentication
     * for the authenticated user.
     *
     * @authenticated
     */
    public function disableAuthenticator(Request $request)
    {
        $this->twoFactorAuthService->disableAuthenticator(
            $request->user()
        );

        return ApiResponse::success(
            'Authenticator 2FA disabled successfully'
        );
    }

    /**
     * Regenerate Recovery Codes
     *
     * Generate a new set of recovery codes for authenticator-based
     * two-factor authentication.
     *
     * Recovery codes can be used to access the account if the
     * authenticator device is unavailable.
     *
     * @authenticated
     */
    public function regenerateRecoveryCodes(Request $request)
    {
        $data = $this->twoFactorAuthService->regenerateRecoveryCodes(
            $request->user()
        );

        return ApiResponse::success(
            'Recovery codes regenerated successfully',
            $data
        );
    }
}